{% set name = "qsimcirq" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quantumlib/qsim/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 81101fe9e6356e54125f703956e787aa366717c1e6e77aea794879b53c84ff60
  patches:
    - patches/0005-Allow-installing-for-Python-3.12.patch

build:
  skip: true  # [win]
  number: 1
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pybind11-abi
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - openmpi
    - cmake >=3.27
    - make
  host:
    - python
    - pybind11
    - setuptools >=45
    - wheel
    - pip
    - numpy
  run:
    - python
    - absl-py
    - cirq-core
    - pybind11
    - typing_extensions
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - qsimcirq
  source_files:
    - qsimcirq_tests
  commands:
    - pip check
    - cd qsimcirq_tests && pytest -vvv .
  requires:
    - pip
    - pytest

about:
  home: https://quantumai.google/qsim
  summary: Quantum circuit simulators qsim and qsimh.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - basnijholt
    - BastianZim
