{% set name = "qsimcirq" %}
{% set version = "0.22.0" %}
{% set build = 0 %}

# Prioritize over CPU builds
{% if cuda_compiler_version in (None, "None", True, False) %}
{% set cuda_major = 0 %}
{% set build = build + 200 %}
{% else %}
{% set cuda_major = environ.get("cuda_compiler_version", "11.2").split(".")[0] | int %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quantumlib/qsim/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a7817314a19c7d2d19dc5e32df318f7a784b9a6ee5a48670ed99054d85b614c4
  patches:
    - patches/0007-Always-skip-test_cirq_qsim_gpu_amplitudes-because-no.patch  # [cuda_compiler_version != "None"]
    - patches/0010-Do-not-set-includes-on-Apple-arm64-in-basis.patch

build:
  skip: true  # [win]
  number: {{ build }}
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  ignore_run_exports_from:
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
  script_env:
    - CUQUANTUM_ROOT=$PREFIX  # [cuda_compiler_version != "None"]
    - CUDAARCHS=70-real;75-real;80-real;86-real;89-real;90  # [cuda_compiler_version != "None"]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - cmake >=3.27
    - make
  host:
    - python
    - pybind11
    - pybind11-abi
    - setuptools >=45
    - wheel
    - pip
    - packaging
    - numpy
    - llvm-openmp  # [osx]
    - custatevec                                # [cuda_compiler_version != "None"]
    - libcublas-dev                             # [(cuda_compiler_version or "").startswith("12")]
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
  run:
    - python
    - absl-py
    - cirq-core
    - typing_extensions
    - {{ pin_compatible('custatevec', max_pin='x') }}        # [cuda_compiler_version != "None"]
    - cudatoolkit                                            # [(cuda_compiler_version or "").startswith("11")]
    - {{ pin_compatible('libcublas', max_pin='x') }}         # [(cuda_compiler_version or "").startswith("12")]
    - cuda-version >={{ cuda_major }}.2,<{{ cuda_major+1 }}  # [(cuda_compiler_version or "").startswith("11")]
    - cuda-version >={{ cuda_major }}.0,<{{ cuda_major+1 }}  # [(cuda_compiler_version or "").startswith("12")]

test:
  imports:
    - qsimcirq
  source_files:
    - qsimcirq_tests
  commands:
    - pip check
    - cd qsimcirq_tests && pytest -vvv .
  requires:
    - pip
    - pytest
    - pybind11

about:
  home: https://quantumai.google/qsim
  summary: Quantum circuit simulators qsim and qsimh.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - basnijholt
    - BastianZim
    - leofang
